Repository neos/flow-development-collection, pull requests merged in 2019-04, with the labels that each got.

#1548 WIP: Merge 5.3 to master
  Neos.Flow/Classes/Command/RoutingCommandController.php
  Neos.Flow/Classes/Error/AbstractExceptionHandler.php
  Neos.Flow/Classes/Http/AbstractMessage.php
  Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
  Neos.Flow/Classes/Http/Response.php
  Neos.Flow/Classes/Mvc/ActionResponse.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/Controller/ControllerContext.php
  Neos.Flow/Classes/Mvc/DispatchComponent.php
  Neos.Flow/Classes/Mvc/Dispatcher.php
  Neos.Flow/Classes/Mvc/Response.php
  Neos.Flow/Classes/Mvc/ResponseDeprecationTrait.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatchComponentTest.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
  Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetComponent.php
  Neos.FluidAdaptor/Classes/View/StandaloneView.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AjaxWidgetComponentTest.php
  Readme.rst
Labels: I: WIP

#1549 BUGFIX: Fix package:create and derived commands when private packagist is used
  Neos.Flow/Classes/Package/PackageManager.php
Labels: Bug, P: Flow, P: Kickstarter

#1536 TASK: Make migrations typesafe and avoid IDE warnings
  Neos.Flow/Classes/Persistence/Doctrine/Service.php
Labels: P: Flow, T: PHP

#1537 BUGFIX: Avoid type error when a non taggable cache backend gets flushed by tag
  Neos.Cache/Classes/Frontend/AbstractFrontend.php
Labels: Bug, P: Cache, T: PHP

#1557 BUGFIX: Fix log environment in logging aspects
  Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
  Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
Labels: P: Flow, T: PHP

#1560 WIP: Merge 4.3 into 5.0
  Neos.Flow/Classes/I18n/Service.php
Labels: I: WIP

#1561 WIP: Merge 5.0 into 5.1
  Neos.Cache/Classes/Frontend/AbstractFrontend.php
  Neos.Flow/Classes/I18n/Service.php
Labels: I: WIP

#1562 WIP: Merge 5.1 into 5.2
  Neos.Cache/Classes/Frontend/AbstractFrontend.php
  Neos.Flow/Classes/I18n/Service.php
Labels: I: WIP

#1563 WIP: Merge 5.2 into 5.3
  Neos.Cache/Classes/Frontend/AbstractFrontend.php
  Neos.Flow/Classes/I18n/Service.php
  Neos.Flow/Classes/Package/PackageManager.php
  Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
  Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
Labels: I: WIP

#1564 WIP: Merge 5.3 to master
  Neos.Cache/Classes/Frontend/AbstractFrontend.php
  Neos.Flow/Classes/I18n/Service.php
  Neos.Flow/Classes/Package/PackageManager.php
  Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
  Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/530.rst
Labels: I: WIP
