Repository neos/flow-development-collection, pull requests merged in 2019-03, with the labels that each got.

#1516 BUGFIX: Allow testing provider everywhere
  Neos.Flow/Configuration/Testing/Settings.yaml
Labels: P: Flow, T: Testing

#1524 MERGE: 4.3 to 5.0
  Neos.Flow/Classes/Command/HelpCommandController.php
  Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php
  Neos.Flow/Configuration/Testing/Settings.yaml
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
Labels: I: WIP

#1525 MERGE: 5.0 to 5.1
  Neos.Flow/Classes/Command/HelpCommandController.php
  Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php
  Neos.Flow/Configuration/Testing/Settings.yaml
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
Labels: I: WIP

#1526 MERGE: 5.1 to 5.2
  Neos.Cache/Classes/Backend/TaggableMultiBackend.php
  Neos.Flow/Classes/Command/HelpCommandController.php
  Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php
  Neos.Flow/Configuration/Testing/Settings.yaml
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
Labels: I: WIP

#1527 MERGE: 5.2 to master
  Neos.Cache/Classes/Backend/TaggableMultiBackend.php
  Neos.Flow/Classes/Command/HelpCommandController.php
  Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php
  Neos.Flow/Configuration/Testing/Settings.yaml
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/AnnotationReference.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/FluidAdaptorViewHelperReference.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/SignalsReference.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/TYPO3FluidViewHelperReference.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/TypeConverterReference.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ValidatorReference.rst
Labels: I: WIP

#1530 BUGFIX: Ignore template/psalm annotations
  TYPO3.Flow/Configuration/Settings.yaml
Labels: P: Flow
