Repository neos/flow-development-collection, pull requests merged in 2020-08, with the labels that each got.

#2050 BUGFIX: Browser arguments are the request parsed body
  Neos.Flow/Classes/Http/Client/Browser.php
  Neos.Flow/Tests/Functional/Http/Client/BrowserTest.php
  Neos.Flow/Tests/Functional/Http/Fixtures/Controller/RequestController.php
Labels: Bug, P: Flow, T: PHP

#2081 BUGFIX: Correct indention for throwables config
  Neos.Flow/Configuration/Settings.Log.yaml
Labels: Bug

#2015 TASK: Test against PHP 8
  .travis.yml
  Neos.Cache/composer.json
  Neos.Eel/composer.json
  Neos.Error.Messages/composer.json
  Neos.Flow.Log/composer.json
  Neos.Flow/composer.json
  Neos.FluidAdaptor/composer.json
  Neos.Http.Factories/composer.json
  Neos.Kickstarter/composer.json
  Neos.Utility.Arrays/composer.json
  Neos.Utility.Files/composer.json
  Neos.Utility.MediaTypes/composer.json
  Neos.Utility.ObjectHandling/composer.json
  Neos.Utility.OpcodeCache/composer.json
  Neos.Utility.Pdo/composer.json
  Neos.Utility.Schema/composer.json
  Neos.Utility.Unicode/composer.json
  composer.json
Labels: !!! Next major, T: Testing
