Repository neos/flow-development-collection, pull requests merged in 2023-03, with the labels that each got.

#2978 Task: EEL Cleanup Context::unwrapValue
  Neos.Eel/Classes/Context.php
Labels: Task, 7.3

#2925 FEATURE: Add cache lifetime to routing MatchResult and ResolveResult DTOs in addition to cache tags
  Neos.Flow/Classes/Mvc/Routing/Dto/MatchResult.php
  Neos.Flow/Classes/Mvc/Routing/Dto/ResolveResult.php
  Neos.Flow/Classes/Mvc/Routing/Dto/RouteLifetime.php
  Neos.Flow/Classes/Mvc/Routing/Route.php
  Neos.Flow/Classes/Mvc/Routing/Router.php
  Neos.Flow/Classes/Mvc/Routing/RouterCachingService.php
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Routing.rst
  Neos.Flow/Resources/Private/Schema/Routes.schema.yaml
  Neos.Flow/Tests/Unit/Mvc/Routing/Dto/RouteLifetimeTest.php
  Neos.Flow/Tests/Unit/Mvc/Routing/RouterTest.php
Labels: Feature

#2793 FEATURE: Provide central `PsrHttpFactory` that implements all interfaces from PSR 17
  Neos.Http.Factories/Classes/FlowUploadedFile.php
  Neos.Http.Factories/Classes/PsrHttpFactory.php
  Neos.Http.Factories/Classes/RequestFactory.php
  Neos.Http.Factories/Classes/RequestFactoryTrait.php
  Neos.Http.Factories/Classes/ResponseFactory.php
  Neos.Http.Factories/Classes/ResponseFactoryTrait.php
  Neos.Http.Factories/Classes/ServerRequestFactory.php
  Neos.Http.Factories/Classes/ServerRequestFactoryTrait.php
  Neos.Http.Factories/Classes/StreamFactory.php
  Neos.Http.Factories/Classes/StreamFactoryTrait.php
  Neos.Http.Factories/Classes/UploadedFileFactory.php
  Neos.Http.Factories/Classes/UploadedFileFactoryTrait.php
  Neos.Http.Factories/Classes/UriFactory.php
  Neos.Http.Factories/Classes/UriFactoryTrait.php
  psalm-baseline.xml
Labels: Feature, 8.3

#2977 TASK: Fix `ProtectedContext` tests
  Neos.Eel/Tests/Unit/ProtectedContextTest.php
Labels: Task, 7.3
