Repository neos/flow-development-collection, pull requests merged in 2023-05, with the labels that each got.

#3030 BUGFIX: Fix JsonArrayTypeTest
  Neos.Flow/Classes/Persistence/Doctrine/DataTypes/JsonArrayType.php
  Neos.Flow/Classes/Persistence/Repository.php
  Neos.Flow/Tests/Unit/Http/Middleware/StandardsComplianceMiddlewareTest.php
  Neos.Flow/Tests/Unit/Http/UriTest.php
  Neos.Flow/Tests/Unit/Persistence/Doctrine/DataTypes/JsonArrayTypeTest.php
  Neos.Flow/Tests/Unit/Persistence/RepositoryTest.php
  Neos.Flow/Tests/Unit/Property/PropertyMappingConfigurationTest.php
  Neos.Flow/Tests/Unit/Security/Aspect/PolicyEnforcementAspectTest.php
Labels: Bug, 8.3

#3038 BUGFIX: Prevent type hint errors with latest Fluid minor release
  Neos.FluidAdaptor/composer.json
  composer.json
Labels: Bug, 7.3

#3040 !!! TASK: Require PHP 8.2
  .github/workflows/build.yml
  Neos.Cache/composer.json
  Neos.Eel/composer.json
  Neos.Flow.Log/composer.json
  Neos.Flow/composer.json
  Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php
  Neos.FluidAdaptor/composer.json
  Neos.Http.Factories/composer.json
  Neos.Kickstarter/composer.json
  Neos.Utility.Arrays/composer.json
  Neos.Utility.Files/composer.json
  Neos.Utility.ObjectHandling/composer.json
  Neos.Utility.Schema/composer.json
  Neos.Utility.Unicode/composer.json
  composer.json
Labels: 9.0

#3041 BUGFIX: Move access to objectAccess of TemplateObjectAccessInterface into getByPath
  Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php
Labels: Bug, 9.0

#2624 BUGFIX: Fix proxy compilation for edge cases
  Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassWithKeywordsInClassBody.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
  Neos.Flow/Tests/Unit/ObjectManagement/Proxy/CompilerTest.php
Labels: P: Flow, Bug, 8.0

#3028 BUGFIX: Widgets can't be nested in For (Fluid)
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
  Neos.FluidAdaptor/Resources/Private/Templates/Tests/Functional/Core/Fixtures/AjaxTest/ForIndex.html
  Neos.FluidAdaptor/Resources/Private/Templates/Tests/Functional/Core/Fixtures/ViewHelpers/SomeAjax/Index.html
  Neos.FluidAdaptor/Tests/Functional/Core/Fixtures/Controller/AjaxTestController.php
  Neos.FluidAdaptor/Tests/Functional/Core/Fixtures/ViewHelpers/Controller/SomeAjaxController.php
  Neos.FluidAdaptor/Tests/Functional/Core/WidgetTest.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AbstractWidgetViewHelperTest.php
Labels: Bug, 7.3

#3035 TASK: Require all collection packages as `self.version`
  Neos.Cache/composer.json
  Neos.Eel/composer.json
  Neos.Flow.Log/composer.json
  Neos.Flow/composer.json
  Neos.FluidAdaptor/composer.json
  Neos.Kickstarter/composer.json
  Neos.Utility.Arrays/composer.json
  Neos.Utility.Files/composer.json
  Neos.Utility.Schema/composer.json
  composer.json
Labels: Task, 7.3

#3047 TASK: Only add serialization entities code if needed
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/Aop/Pointcut/PointcutExpressionParser.php
  Neos.Flow/Classes/Aop/Pointcut/PointcutMethodNameFilter.php
  Neos.Flow/Classes/Cache/CacheFactory.php
  Neos.Flow/Classes/Mvc/Routing/IdentityRoutePart.php
  Neos.Flow/Classes/Mvc/Routing/ObjectPathMapping.php
  Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/ObjectManager.php
  Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ObjectSerializationTrait.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php
  Neos.Flow/Classes/Persistence/Aspect/EmbeddedValueObjectPointcutFilter.php
  Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Flow/Classes/Reflection/ReflectionServiceFactory.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassToBeSerialized.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PrototypeClassF.php
  Neos.Flow/Tests/Functional/ObjectManagement/ObjectSerializationTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
Labels: Task, 9.0

#3053 TASK: Clean up functional tests for AOP
  Neos.Flow/Tests/Functional/Aop/AopProxyTest.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/BaseFunctionalityTestingAspect.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/TargetClassWithPhp7Features.php
  Neos.Flow/Tests/Functional/Aop/FrameworkTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PHP8/ClassWithUnionTypes.php
Labels: Task, 9.0

#3054 TASK: Replace "adviced" by "advised"
  Neos.Flow/Classes/Aop/Builder/AdvisedConstructorInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/AdvisedMethodInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/AspectOrientedProgramming.rst
  Neos.Flow/Tests/Functional/Aop/AopProxyTest.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/AbstractClassTestingAspect.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/BaseFunctionalityTestingAspect.php
  Neos.Flow/Tests/Functional/Aop/FrameworkTest.php
  Neos.Flow/Tests/Unit/Aop/Builder/AbstractMethodInterceptorBuilderTest.php
  Neos.Flow/Tests/Unit/ObjectManagement/Fixture/BasicClass.php
  psalm-baseline.xml
Labels: Task, 9.0

#3055 TASK: Clean up code in AOP and ObjectManagement
  Neos.Flow/Classes/Aop/Builder/AbstractMethodInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/AdvisedConstructorInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/AdvisedMethodInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/ClassNameIndex.php
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/Aop/Pointcut/PointcutClassAnnotatedWithFilter.php
  Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructor.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/BaseFunctionalityTestingAspect.php
  Neos.Flow/Tests/Functional/Aop/FrameworkTest.php
Labels: Task, 9.0

#3063 BUGFIX: Create serialization code for transient properties
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Labels: Bug, 9.0

#3032 BUGFIX: No usage of dynamic properties
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/PropertyInjectionTrait.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ObjectSerializationTrait.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
Labels: Bug, 8.0
