Repository neos/flow-development-collection, pull requests merged in 2023-09, with the labels that each got.

#3156 BUGFIX: Prevent deprecation warning in `RouteTags::createFromArray()`
  Neos.Flow/Classes/Mvc/Routing/Dto/RouteTags.php
Labels: Bug, 7.3

#3176 Apply fixes from StyleCI
  Neos.Flow/Tests/Functional/Aop/Fixtures/TargetClassWithPhp8Features.php
Labels: 9.0

#3162 BUGFIX: 3129 ProxyClassBuilder php 8.0 fix `get_class_methods`
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
Labels: Bug, 7.3

#3183 BUGFIX: Fix `ConfigurationManager::setTemporaryDirectoryBase()` for PHP 8+
  Neos.Flow/Classes/Configuration/ConfigurationManager.php
  Neos.Flow/Tests/Functional/Configuration/ConfigurationManagerTest.php
Labels: Bug, 7.3

#3180 BUGFIX: Allow arrays in `replace`-String-Helper
  Neos.Eel/Classes/Helper/StringHelper.php
  Neos.Eel/Tests/Unit/Helper/StringHelperTest.php
Labels: Bug, Feature, 7.3

#3173 TASK: document and deprecate flows internal isolated behat tests
  Neos.Flow/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Flow/Tests/Behavior/Features/Bootstrap/IsolatedBehatStepsTrait.php
  Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
  Neos.Flow/Tests/Behavior/Features/Bootstrap/SubProcess/SubProcess.php
  Neos.Flow/Tests/Functional/Command/BehatHelperCommandController.php
  Neos.Flow/Tests/Functional/Command/BehatTestHelper.php
  Neos.Flow/Tests/Functional/Command/PyStringNode.php
  Neos.Flow/Tests/Functional/Command/PyStringNodeConverter.php
  Neos.Flow/Tests/Functional/Command/TableNode.php
  Neos.Flow/Tests/Functional/Command/TableNodeConverter.php
Labels: Task, 9.0

#3175 Task: minor behat test cleanup
  .composer.json
  .github/workflows/build.yml
  .github/workflows/experimental.yml
  Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
  Neos.Flow/Tests/Behavior/behat.yml
  Neos.Flow/Tests/Behavior/behat.yml.dist
  Neos.Flow/Tests/Functional/Command/BehatTestHelper.php
  composer.json
Labels: Task, 9.0

#3146 BUGFIX: Fix `RedisBackend` to allow scheme in hostname
  Neos.Cache/Classes/Backend/RedisBackend.php
Labels: Bug, 7.3

#3184 BUGFIX: Add PDO driverOptions
  Neos.Cache/Classes/Backend/PdoBackend.php
Labels: Bug, 7.3
