Repository neos/flow-development-collection, pull requests merged in 2023-06, with the labels that each got.

#3064 TASK: Use Laminas Code for proxy method rendering
  Neos.Flow/Classes/Aop/Builder/AdvisedConstructorInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/AdvisedMethodInterceptorBuilder.php
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructor.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructorGenerator.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethodGenerator.php
  Neos.Flow/Configuration/Settings.Reflection.yaml
  Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
  Neos.Flow/Tests/Unit/ObjectManagement/Proxy/ProxyClassTest.php
  Neos.Flow/Tests/Unit/ObjectManagement/Proxy/ProxyMethodTest.php
  Neos.Flow/composer.json
Labels: Task, 9.0

#3067 BUGFIX: Remove injected properties before serialization
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Labels: Bug, 9.0

#3072 FEATURE: Support private constructors in proxy classes
  Neos.Flow/Classes/ObjectManagement/Exception/ProxyCompilerException.php
  Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructorGenerator.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/AbstractClassWithFactoryMethod.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassExtendingClassWithPrivateConstructor.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassWithPrivateConstructor.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
Labels: Feature, 9.0

#3071 TASK: Support PHP never, null, false, and true as stand-alone types
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethodGenerator.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/BaseFunctionalityTestingAspect.php
  Neos.Flow/Tests/Functional/Aop/Fixtures/TargetClassWithPhp8Features.php
  Neos.Flow/Tests/Functional/Aop/FrameworkTest.php
Labels: Task, 9.0

#3088 BUGFIX: Normalize windows package paths
  Neos.Flow/Classes/Package/PackageManager.php
Labels: Bug, 8.3, Windows

#3101 BUGFIX: Replacement proxy methods rendered again
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethodGenerator.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PrototypeClassK.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
  Neos.Flow/Tests/Functional/Persistence/Aspect/PersistenceMagicAspectTest.php
Labels: Bug, 9.0
