Repository neos/flow-development-collection, pull requests merged in 2023-12, with the labels that each got.

#3249 Revert "BUGFIX: Sanitize uploaded svg files for suspicious contents"
  Neos.Flow/Classes/ResourceManagement/ResourceManager.php
  Neos.Flow/composer.json
  Neos.Utility.MediaTypes/Classes/MediaTypes.php
  Neos.Utility.MediaTypes/Tests/Unit/MediaTypesTest.php
  composer.json
Labels: Bug, 7.3, 8.3, 8.2, 8.0

#3252 TASK: Correct Flow composer.json
  Neos.Flow/composer.json
Labels: Task, 8.0

#3244 FEATURE: Add `Flow\InjectCache` Attribute / Annotation for property injection
  Neos.Flow/Classes/Annotations/InjectCache.php
  Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
  Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationProperty.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassWithInjectedCache.php
Labels: T: PHP, P: Flow, Feature, 9.0
