Repository neos/flow-development-collection, pull requests merged in 2023-10, with the labels that each got.

#3194 TASK: Fix cache RedisBackend unittest
  Neos.Cache/Tests/Unit/Backend/RedisBackendTest.php
Labels: Task, 8.0

#3195 TASK: Fix documentation builds
  Neos.Flow/Documentation/requirements.in
  Neos.Flow/Documentation/requirements.txt
Labels: Task, 7.3

#3196 TASK: Fix cache RedisBackend unittest
  Neos.Cache/Tests/Unit/Backend/RedisBackendTest.php
Labels: Task, 7.3

#3172 BUGFIX: Sanitize uploaded svg files from suspicious content
  Neos.Flow/Classes/ResourceManagement/ResourceManager.php
  Neos.Flow/composer.json
  Neos.Utility.MediaTypes/Classes/MediaTypes.php
  Neos.Utility.MediaTypes/Tests/Unit/MediaTypesTest.php
  composer.json
Labels: Bug, 7.3

#3140 BUGFIX: Only set distinct on count clause if explicitely set to improve performance
  Neos.Flow/Classes/Persistence/Doctrine/CountWalker.php
Labels: Bug, 7.3

#3149 FEATURE: Add `getAccessorByPath` to `Neos\Utility\Arrays` for type safe accessing of array values
  Neos.Utility.Arrays/Classes/Arrays.php
  Neos.Utility.Arrays/Classes/ValueAccessor.php
  Neos.Utility.Arrays/Tests/Unit/ArraysTest.php
  Neos.Utility.Arrays/Tests/Unit/ValueAccessorTest.php
Labels: Feature, 9.0

#3102 9.0 FEATURE: Add `unique` flowQuery operation
  Neos.Eel/Classes/FlowQuery/Operations/UniqueOperation.php
  Neos.Eel/Tests/Unit/FlowQuery/Operations/UniqueOperationTest.php
Labels: P: Eel, Feature, 9.0

#3206 BUGFIX: Require collection packages as `self.version` again
  Neos.Eel/composer.json
  Neos.Flow/composer.json
  Neos.FluidAdaptor/composer.json
  Neos.Kickstarter/composer.json
Labels: Bug, 7.3

#3207 TASK: Fix overlooked dependency…
  Neos.Flow/composer.json
Labels: Task, 7.3
