Repository neos/flow-development-collection, pull requests merged in 2023-07, with the labels that each got.

#3096 BUGFIX: If bytes to read is not > 0, return empty string
  Neos.Cache/Classes/Backend/SimpleFileBackend.php
Labels: Bug, 7.3

#3107 Apply fixes from StyleCI
  Neos.Flow/Classes/Configuration/ConfigurationManager.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Utility.ObjectHandling/Classes/TypeHandling.php
Labels: 7.3

#3094 TASK: PHP 8.1 deprecations compatibility
  Neos.Cache/Classes/Backend/ApcuBackend.php
  Neos.Cache/Classes/Backend/PdoBackend.php
  Neos.Cache/Classes/Backend/RedisBackend.php
  Neos.Cache/Classes/Backend/SimpleFileBackend.php
  Neos.Cache/Classes/Frontend/CacheEntryIterator.php
  Neos.Cache/Tests/Unit/Backend/FileBackendTest.php
  Neos.Eel/Classes/FlowQuery/FlowQuery.php
  Neos.Eel/Classes/FlowQuery/Operations/Object/FilterOperation.php
  Neos.Eel/Classes/Helper/MathHelper.php
  Neos.Eel/Classes/Helper/StringHelper.php
  Neos.Eel/Tests/Unit/Fixtures/TestArrayIterator.php
  Neos.Flow.Log/Classes/Backend/FileBackend.php
  Neos.Flow/Classes/Http/Cookie.php
  Neos.Flow/Classes/Http/Headers.php
  Neos.Flow/Classes/Http/RequestHandler.php
  Neos.Flow/Classes/Mvc/Controller/Arguments.php
  Neos.Flow/Classes/Mvc/Routing/IdentityRoutePart.php
  Neos.Flow/Classes/Mvc/Routing/StaticRoutePart.php
  Neos.Flow/Classes/Persistence/Doctrine/QueryResult.php
  Neos.Flow/Classes/Persistence/EmptyQueryResult.php
  Neos.Flow/Classes/Reflection/ClassReflection.php
  Neos.Flow/Classes/Reflection/MethodReflection.php
  Neos.Flow/Classes/Reflection/ParameterReflection.php
  Neos.Flow/Classes/Reflection/PropertyReflection.php
  Neos.Flow/Classes/Security/Cryptography/Algorithms.php
  Neos.Flow/Classes/Validation/Validator/AbstractCompositeValidator.php
  Neos.Flow/Classes/Validation/Validator/TextValidator.php
  Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
  Neos.Flow/Tests/Unit/Property/PropertyMappingConfigurationTest.php
  Neos.Flow/Tests/Unit/Property/TypeConverter/DateTimeConverterTest.php
  Neos.Flow/Tests/Unit/Reflection/Fixture/ArrayAccessClass.php
  Neos.FluidAdaptor/Classes/ViewHelpers/Form/SelectViewHelper.php
  Neos.FluidAdaptor/Classes/ViewHelpers/Form/TextareaViewHelper.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AbstractWidgetControllerTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/FormViewHelperTest.php
  Neos.Utility.Arrays/Classes/Arrays.php
  Neos.Utility.Files/Classes/Files.php
  Neos.Utility.ObjectHandling/Tests/Unit/Fixture/ArrayAccessClass.php
  Neos.Utility.Unicode/Classes/TextIterator.php
  psalm-baseline.xml
Labels: Task, 7.3

#3114 TASK: Fix settings for reference rendering
  Neos.FluidAdaptor/Configuration/Settings.yaml
Labels: Task, 7.3

#3117 TASK: Avoid potential deprecation warning in StringHelper
  Neos.Eel/Classes/Helper/StringHelper.php
Labels: Task, 7.3
