Repository neos/flow-development-collection, pull requests merged in 2023-11, with the labels that each got.

#3187 TASK: Clean up stored throwable dumps
  Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
  Neos.Flow/Configuration/Settings.Log.yaml
Labels: Task, 7.3

#3208 TASK: Use new Behat `FlowBootstrapTrait`
  .composer.json
  Neos.Flow/Configuration/Settings.Reflection.yaml
  Neos.Flow/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Flow/Tests/Behavior/Features/Bootstrap/IsolatedBehatStepsTrait.php
  Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
  Neos.Flow/Tests/Behavior/Features/Security/Policy.method.feature
  Neos.Flow/Tests/Functional/Command/BehatTestHelper.php
  composer.json
Labels: Task, 9.0

#3210 BUGFIX: Use method to set validated instances container
  Neos.Flow/Classes/Validation/Validator/AbstractCompositeValidator.php
Labels: Bug, 7.3

#3213 TASK: Update default settings for stored throwable dumps
  Neos.Flow/Configuration/Settings.Log.yaml
Labels: Task, 9.0

#3209 BUGFIX: Use correct exception class
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
Labels: Bug, 9.0

#3199 TASK: Carefully fix psalm types across codebase to make it green ;)
  Neos.Eel/Classes/Helper/MathHelper.php
  Neos.Eel/Classes/Helper/StringHelper.php
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/Aop/Pointcut/PointcutClassAnnotatedWithFilter.php
  Neos.Flow/Classes/Aop/Pointcut/PointcutFilter.php
  Neos.Flow/Classes/Cli/CommandManager.php
  Neos.Flow/Classes/Cli/RequestBuilder.php
  Neos.Flow/Classes/Core/Booting/Scripts.php
  Neos.Flow/Classes/ObjectManagement/ObjectManager.php
  Neos.Flow/Classes/ObjectManagement/ObjectManagerInterface.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructorGenerator.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethodGenerator.php
  Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
  Neos.Flow/Classes/Reflection/ClassSchema.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Flow/Classes/Session/Aspect/LazyLoadingAspect.php
  Neos.Flow/Classes/Session/Session.php
  Neos.FluidAdaptor/Classes/ViewHelpers/Form/SelectViewHelper.php
  psalm-baseline.xml
Labels: Task, 9.0

#3215 TASK: PEG Parser declares properties
  Neos.Eel/Resources/Private/PHP/php-peg/Parser.php
Labels: Task, 7.3

#3216 TASK: Migrate to PHPStan (adjustments in Flow 9)
  .composer.json
  Neos.Cache/Classes/Backend/TaggableMultiBackend.php
  Neos.Eel/Classes/FlowQuery/Operations/Object/FilterOperation.php
  Neos.Eel/Classes/Helper/MathHelper.php
  Neos.Eel/Classes/Helper/StringHelper.php
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
  Neos.Flow/Classes/Cli/CommandController.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/Controller/RestController.php
  Neos.Flow/Classes/Mvc/Routing/Dto/MatchResult.php
  Neos.Flow/Classes/Mvc/Routing/Dto/ResolveResult.php
  Neos.Flow/Classes/Mvc/Routing/ObjectPathMapping.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructorGenerator.php
  Neos.Flow/Classes/Persistence/EmptyQueryResult.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Flow/Classes/Security/Authentication/Controller/AbstractAuthenticationController.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  composer.json
Labels: Task, 9.0

#3223 TASK: Remove persistence clone magic
  Neos.Flow/Classes/Persistence/Aspect/PersistenceMagicAspect.php
  Neos.Flow/Tests/Functional/Persistence/Aspect/PersistenceMagicAspectTest.php
  Neos.Flow/Tests/Unit/Persistence/Aspect/PersistenceMagicAspectTest.php
  Neos.Flow/Tests/Unit/Property/TypeConverter/PersistentObjectConverterTest.php
Labels: Task, 9.0

#3222 TASK: Use generics via @template instead of PHPSTORM_META
  Neos.Eel/Classes/FlowQuery/OperationResolver.php
  Neos.Flow/.phpstorm.meta.php
  Neos.Flow/Classes/Core/Bootstrap.php
  Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
  Neos.Flow/Classes/ObjectManagement/ObjectManager.php
  Neos.Flow/Classes/ObjectManagement/ObjectManagerInterface.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Utility.Arrays/Classes/ValueAccessor.php
Labels: Task, 9.0

#3226 BUGFIX: Return the expected result for `is_dir('resource://sha1')`
  Neos.Flow/Classes/ResourceManagement/Streams/ResourceStreamWrapper.php
  Neos.Flow/Tests/Unit/ResourceManagement/Streams/ResourceStreamWrapperTest.php
Labels: Bug, 7.3

#3231 TASK: Routing Documentation Adjustment
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Routing.rst
Labels: Task, 7.3

#3234 BUGFIX: Set InvalidHashException status code to 400
  Neos.Flow/Classes/Security/Exception/InvalidHashException.php
Labels: Bug, 7.3

#3233 BUGFIX: Make new object debug output more robust
  Neos.Eel/Classes/Context.php
  Neos.Eel/Classes/InterpretedEelParser.php
  Neos.Flow/Classes/Error/Debugger.php
Labels: Bug, 9.0

#3238 TASK: Update default .htaccess for _Resources
  Neos.Flow/Resources/Private/Installer/Distribution/Defaults/Web/_Resources/.htaccess
Labels: Task, 7.3

#3240 BUGFIX: No useless read in `FileBackend` (improve performance)
  Neos.Cache/Classes/Backend/FileBackend.php
Labels: Bug, Task, 8.0

#3242 BUGFIX: Update requirements.txt
  Neos.Flow/Documentation/requirements.txt
Labels: Bug, 7.3

#3243 TASK: Add PHP 8.3 to build workflow matrix
  .github/workflows/build.yml
  Neos.Flow/Tests/Functional/Aop/FrameworkTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
Labels: Task, 8.0
