Repository neos/flow-development-collection, pull requests merged in 2023-04, with the labels that each got.

#3011 FEATURE: Add `Type.debugType` to Type EelHelper
  Neos.Eel/Classes/Helper/TypeHelper.php
Labels: Feature, 8.3

#2979 TASK: Test and Fix Utility::parseEelExpression
  Neos.Eel/Classes/Package.php
  Neos.Eel/Classes/Utility.php
  Neos.Eel/Tests/Unit/EelExpressionRecognizerTest.php
Labels: Task, 8.3

#2999 TASK: Relax symfony component constraints to allow version 6.0
  Neos.Flow/composer.json
  composer.json
Labels: Task, 8.3

#3019 TASK: Upgrade psalm to version 4.30.0
  Neos.Flow/composer.json
  composer.json
  psalm-baseline.xml
Labels: Task, 7.3

#3020 BUGFIX: Adjust psalm baseline
  psalm-baseline.xml
Labels: Bug, 7.3

#3017 BUGFIX: Adjust FLOW_VERSION_BRANCH
  Neos.Flow/Classes/Core/Bootstrap.php
Labels: Bug, 8.2

#3018 TASK: Adjust FLOW_VERSION_BRANCH
  Neos.Flow/Classes/Core/Bootstrap.php
Labels: Task, 8.3
