Repository neos/flow-development-collection, pull requests merged in 2024-09, with the labels that each got.

#3390 BUGFIX: Fix support for typo3fluid/fluid 2.15
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/CropViewHelperTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/HtmlentitiesDecodeViewHelperTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/HtmlentitiesViewHelperTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/PaddingViewHelperTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/UrlencodeViewHelperTest.php
  Neos.FluidAdaptor/Tests/Unit/ViewHelpers/ViewHelperBaseTestcase.php
Labels: Bug, 9.0

#3391 Flow: Error message from FileSizeValidator is wrong
  Neos.Flow/Classes/Validation/Validator/FileSizeValidator.php
Labels: 8.3

#3296 !!! TASK: `Mvc\Dispatcher::afterControllerInvocation` will not be called for CLI requests anymore.
  Neos.Flow/Classes/Cli/Dispatcher.php
  Neos.Flow/Classes/Package.php
Labels: 9.0

#3311 !!! FEATURE: Dispatcher psr overhaul
  Neos.Flow/Classes/Http/RequestHandler.php
  Neos.Flow/Classes/Mvc/ActionRequest.php
  Neos.Flow/Classes/Mvc/ActionResponse.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/Controller/ControllerContext.php
  Neos.Flow/Classes/Mvc/Controller/ControllerInterface.php
  Neos.Flow/Classes/Mvc/Controller/RestController.php
  Neos.Flow/Classes/Mvc/Controller/StandardController.php
  Neos.Flow/Classes/Mvc/DispatchMiddleware.php
  Neos.Flow/Classes/Mvc/Dispatcher.php
  Neos.Flow/Classes/Mvc/Exception/ForwardException.php
  Neos.Flow/Classes/Mvc/Exception/StopActionException.php
  Neos.Flow/Classes/Mvc/Exception/UnsupportedRequestTypeException.php
  Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
  Neos.Flow/Tests/Functional/Http/Fixtures/Controller/FooController.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatchMiddlewareTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php
  Neos.Flow/Tests/Unit/Session/SessionManagerTest.php
  Neos.Flow/Tests/Unit/Session/SessionTest.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetController.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
  Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetMiddleware.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AbstractWidgetControllerTest.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AjaxWidgetMiddlewareTest.php
Labels: 9.0

#3301 !!! TASK: Remove dispatched state from ActionRequest
  Neos.Flow/Classes/Mvc/ActionRequest.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ControllerInterface.php
  Neos.Flow/Classes/Mvc/Dispatcher.php
  Neos.Flow/Classes/Mvc/RequestInterface.php
  Neos.Flow/Tests/Unit/Mvc/ActionRequestTest.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
Labels: 9.0

#3386 FEATURE: Introduce EEL tracer for handling Neos9 deprecations
  Neos.Eel/Classes/Context.php
  Neos.Eel/Classes/EelInvocationTracerInterface.php
  Neos.Eel/Classes/Utility.php
Labels: Feature, 8.4

#3396 TASK: Adjust log level of authentication messages
  Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
Labels: Task, 8.4
