Repository neos/flow-development-collection, pull requests merged in 2024-07, with the labels that each got.

#3374 BUGFIX: DateTime translation for validator
  Neos.Flow/Resources/Private/Translations/ar/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/cs/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/da/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/de/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/el/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/en/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/es/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/fi/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/fr/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/hu/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/id_ID/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/it/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/ja/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/km/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/lv/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/nl/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/no/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/pl/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/pt/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/pt_BR/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/ru/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/sr/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/sv/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/tl_PH/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/tr/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/uk/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/vi/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/zh/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/zh_TW/ValidationErrors.xlf
Labels: Bug, 8.3

#3350 FEATURE: Allow `PositionalArraySorter` to keep `null` values
  Neos.Utility.Arrays/Classes/PositionalArraySorter.php
  Neos.Utility.Arrays/Tests/Unit/PositionalArraySorterTest.php
Labels: Feature, 9.0

#3356 TASK: Update "egulias/email-validator" version constraints
  Neos.Flow/composer.json
  composer.json
Labels: Task, 8.3

#3377 FEATURE: Support doctrine/dbal 2.x and 3.x
  Neos.Flow/Classes/Command/DatabaseCommandController.php
  Neos.Flow/Classes/Command/DoctrineCommandController.php
  Neos.Flow/Classes/Persistence/Doctrine/AllowedObjectsListener.php
  Neos.Flow/Classes/Persistence/Doctrine/CacheAdapter.php
  Neos.Flow/Classes/Persistence/Doctrine/DataTypes/JsonArrayType.php
  Neos.Flow/Classes/Persistence/Doctrine/EntityManagerConfiguration.php
  Neos.Flow/Classes/Persistence/Doctrine/Query.php
  Neos.Flow/Configuration/Settings.Persistence.yaml
  Neos.Flow/Tests/Functional/Persistence/Fixtures/ExtendedTypesEntity.php
  Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
  Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
  Neos.Flow/composer.json
  composer.json
Labels: Feature, 8.4

#3379 !!!TASK: Deprecate outdated doctrine functionality
  Neos.Flow/Classes/Persistence/Doctrine/DataTypes/ObjectArray.php
  Neos.Flow/Classes/Persistence/Doctrine/Repository.php
  Neos.Flow/Classes/Persistence/Doctrine/Service.php
Labels: Task, 8.4
