Repository neos/flow-development-collection, pull requests merged in 2024-03, with the labels that each got.

#3294 !!! TASK: Deprecate and replace `ActionResponse` in dispatcher
  Neos.Flow/Classes/Mvc/ActionResponse.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/Controller/ControllerContext.php
  Neos.Flow/Classes/Mvc/Controller/ControllerInterface.php
  Neos.Flow/Classes/Mvc/Controller/RestController.php
  Neos.Flow/Classes/Mvc/DispatchMiddleware.php
  Neos.Flow/Classes/Mvc/Dispatcher.php
  Neos.Flow/Classes/Mvc/Exception/StopActionException.php
  Neos.Flow/Classes/Mvc/View/ViewInterface.php
  Neos.Flow/Tests/Functional/Http/Fixtures/Controller/FooController.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatchMiddlewareTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetController.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
  Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetMiddleware.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AbstractWidgetControllerTest.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AjaxWidgetMiddlewareTest.php
Labels: Task, feature/dispatcher-returns-psr-responses

#3275 TASK: `resource:clean` followup #1678
  Neos.Flow/Classes/Command/ResourceCommandController.php
Labels: Task, 9.0

#3328 FEATURE: Introduce PHP 8.2 DNF type support
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PHP8/ClassWithUnionTypes.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
  Neos.Flow/Tests/Functional/Reflection/Fixtures/PHP8/DummyClassWithDisjunctiveNormalFormTypes.php
  Neos.Flow/Tests/Functional/Reflection/Fixtures/PHP8/DummyClassWithUnionTypeHints.php
  Neos.Flow/Tests/Functional/Reflection/ReflectionServiceTest.php
Labels: Feature, 9.0

#3254 TASK: Refactor and optimize of session data storage
  Neos.Flow/Classes/Session/Data/SessionIdentifier.php
  Neos.Flow/Classes/Session/Data/SessionKeyValueStore.php
  Neos.Flow/Classes/Session/Data/SessionMetaData.php
  Neos.Flow/Classes/Session/Data/SessionMetaDataStore.php
  Neos.Flow/Classes/Session/Data/StorageIdentifier.php
  Neos.Flow/Classes/Session/Exception/InvalidDataInSessionDataStoreException.php
  Neos.Flow/Classes/Session/Session.php
  Neos.Flow/Classes/Session/SessionInterface.php
  Neos.Flow/Classes/Session/SessionManager.php
  Neos.Flow/Configuration/Caches.yaml
  Neos.Flow/Configuration/Objects.yaml
  Neos.Flow/Configuration/Settings.Session.yaml
  Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.session.schema.yaml
  Neos.Flow/Tests/Unit/Session/Data/SessionKeyValueStoreTest.php
  Neos.Flow/Tests/Unit/Session/Data/SessionMetaDataStoreTest.php
  Neos.Flow/Tests/Unit/Session/Data/SessionMetaDataTest.php
  Neos.Flow/Tests/Unit/Session/SessionManagerTest.php
  Neos.Flow/Tests/Unit/Session/SessionTest.php
Labels: Task, 9.0

#3268 TASK: Improve help text for doctrine:migrate
  Neos.Flow/Classes/Command/DoctrineCommandController.php
Labels: Task, 9.0

#3086 FEATURE: InjectConfiguration for constructor arguments
  Neos.Flow/Classes/Annotations/InjectConfiguration.php
  Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/CommandLine.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Configuration.rst
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
  Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PrototypeClassL.php
Labels: Feature, 9.0

#3330 !!! TASK: Modernize and clean up session-related code
  Neos.Flow/Classes/Session/Aspect/LazyLoadingAspect.php
  Neos.Flow/Classes/Session/Aspect/LazyLoadingProxyInterface.php
  Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
  Neos.Flow/Classes/Session/Aspect/SessionObjectMethodsPointcutFilter.php
  Neos.Flow/Classes/Session/CookieEnabledInterface.php
  Neos.Flow/Classes/Session/Data/SessionIdentifier.php
  Neos.Flow/Classes/Session/Data/SessionKeyValueStore.php
  Neos.Flow/Classes/Session/Data/SessionMetaData.php
  Neos.Flow/Classes/Session/Data/SessionMetaDataStore.php
  Neos.Flow/Classes/Session/Data/StorageIdentifier.php
  Neos.Flow/Classes/Session/Exception.php
  Neos.Flow/Classes/Session/Exception/DataNotSerializableException.php
  Neos.Flow/Classes/Session/Exception/InvalidDataInSessionDataStoreException.php
  Neos.Flow/Classes/Session/Exception/InvalidRequestHandlerException.php
  Neos.Flow/Classes/Session/Exception/InvalidRequestResponseException.php
  Neos.Flow/Classes/Session/Exception/OperationNotSupportedException.php
  Neos.Flow/Classes/Session/Exception/SessionAutostartIsEnabledException.php
  Neos.Flow/Classes/Session/Exception/SessionNotStartedException.php
  Neos.Flow/Classes/Session/Session.php
  Neos.Flow/Classes/Session/SessionInterface.php
  Neos.Flow/Classes/Session/SessionManager.php
  Neos.Flow/Classes/Session/SessionManagerInterface.php
  Neos.Flow/Classes/Session/TransientSession.php
  Neos.Flow/Configuration/Objects.yaml
  Neos.Flow/Tests/Unit/Http/Middleware/SessionMiddlewareTest.php
  Neos.Flow/Tests/Unit/Security/Authentication/AuthenticationProviderManagerTest.php
  Neos.Flow/Tests/Unit/Session/SessionManagerTest.php
  Neos.Flow/Tests/Unit/Session/SessionTest.php
Labels: Task, 9.0

#3332 TASK: Declare `ValueAccessor` as experimental for now
  Neos.Utility.Arrays/Classes/Arrays.php
  Neos.Utility.Arrays/Classes/ValueAccessor.php
Labels: Task, 9.0

#3316 FEATURE: introduce `Neos\Flow\Http\UriHelper` to work with query parameters
  Neos.Flow/Classes/Http/BaseUriProvider.php
  Neos.Flow/Classes/Http/UriHelper.php
  Neos.Flow/Tests/Unit/Http/UriHelperTest.php
  Neos.Flow/Tests/Unit/Http/UriTest.php
  Neos.Http.Factories/Classes/PsrHttpFactory.php
  Neos.Http.Factories/Classes/UriFactoryTrait.php
Labels: Feature, 9.0

#3309 TASK: Deprecate BaseTestCase functionalities
  Neos.Flow/Tests/AccessibleProxyInterface.php
  Neos.Flow/Tests/BaseTestCase.php
Labels: Task, 9.0

#3336 TASK: 3316 followup merge uri helpers
  Neos.Flow/Classes/Http/Helper/UriHelper.php
  Neos.Flow/Classes/Http/UriHelper.php
  Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
  Neos.Flow/Tests/Unit/Http/Helper/UriHelperTest.php
Labels: Task, 9.0
