Repository neos/flow-development-collection, pull requests merged in 2024-02, with the labels that each got.

#3299 TASK: Fix errors in Middleware code example
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
Labels: T: Documentation, Task, 7.3

#3201 TASK: Followup ValueAccessor
  Neos.Utility.Arrays/Classes/Arrays.php
  Neos.Utility.Arrays/Classes/ValueAccessor.php
  Neos.Utility.Arrays/Tests/Unit/ValueAccessorTest.php
Labels: Task, 9.0

#3179 BUGFIX: More descriptive reflection error if attribute does not exist
  Neos.Flow/Classes/Reflection/ReflectionService.php
Labels: Bug, 8.3

#3232 !!! FEATURE: WIP Dispatcher and controller return `ActionResponse` (simpler controller pattern)
  Neos.Flow/Classes/Mvc/ActionRequest.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/Controller/ControllerInterface.php
  Neos.Flow/Classes/Mvc/Controller/RestController.php
  Neos.Flow/Classes/Mvc/Controller/StandardController.php
  Neos.Flow/Classes/Mvc/DispatchMiddleware.php
  Neos.Flow/Classes/Mvc/Dispatcher.php
  Neos.Flow/Classes/Mvc/Exception/ForwardException.php
  Neos.Flow/Classes/Mvc/Exception/StopActionException.php
  Neos.Flow/Classes/Mvc/Exception/UnsupportedRequestTypeException.php
  Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
  Neos.Flow/Tests/Functional/Http/Fixtures/Controller/FooController.php
  Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatchMiddlewareTest.php
  Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetController.php
  Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
  Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetMiddleware.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AbstractWidgetControllerTest.php
  Neos.FluidAdaptor/Tests/Unit/Core/Widget/AjaxWidgetMiddlewareTest.php
Labels: feature/dispatcher-returns-psr-responses

#3171 TASK: Scripts.php avoid use of same references for exec
  Neos.Flow/Classes/Core/Booting/Scripts.php
Labels: Task, 7.3

#2697 BUGFIX: Web-Exception messages preserve whitespace (ASCII Art)
  Neos.Flow/Classes/Error/DebugExceptionHandler.php
  Neos.Flow/Resources/Public/Error/Exception.css
Labels: I: Discussion, Bug, Stale, 8.3

#3033 TASK: ObjectManagement limit debugBacktrace
  Neos.Flow/Classes/ObjectManagement/Configuration/Configuration.php
Labels: Task, 8.3

#3308 TASK: Add type hints and minimal cleanup in object manager
  Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
  Neos.Flow/Classes/ObjectManagement/ObjectManager.php
Labels: Task, 9.0

#2970 FEATURE: Separate RouteConfiguration from Router
  Neos.Flow/Classes/Command/RoutingCommandController.php
  Neos.Flow/Classes/Mvc/Routing/ConfigurationRoutesProvider.php
  Neos.Flow/Classes/Mvc/Routing/Route.php
  Neos.Flow/Classes/Mvc/Routing/Router.php
  Neos.Flow/Classes/Mvc/Routing/Routes.php
  Neos.Flow/Classes/Mvc/Routing/RoutesProviderInterface.php
  Neos.Flow/Classes/Mvc/Routing/TestingRoutesProvider.php
  Neos.Flow/Configuration/Objects.yaml
  Neos.Flow/Configuration/Testing/Objects.yaml
  Neos.Flow/Tests/Functional/Http/Client/InternalRequestEngineTest.php
  Neos.Flow/Tests/Functional/Http/RequestHandlerTest.php
  Neos.Flow/Tests/Functional/Mvc/AbstractControllerTest.php
  Neos.Flow/Tests/Functional/Mvc/RoutingTest.php
  Neos.Flow/Tests/Functional/Mvc/UriBuilderTest.php
  Neos.Flow/Tests/Functional/Security/AuthenticationTest.php
  Neos.Flow/Tests/Functional/Session/SessionManagementTest.php
  Neos.Flow/Tests/FunctionalTestCase.php
  Neos.Flow/Tests/Unit/Mvc/Routing/ConfigurationRoutesProviderTest.php
  Neos.Flow/Tests/Unit/Mvc/Routing/RouterTest.php
  Neos.Flow/Tests/Unit/Mvc/Routing/RoutesTest.php
  Neos.Flow/Tests/Unit/Mvc/Routing/RoutingMiddlewareTest.php
  Neos.FluidAdaptor/Tests/Functional/Core/WidgetTest.php
  Neos.FluidAdaptor/Tests/Functional/Form/FormObjectsTest.php
Labels: Feature, 9.0

#3247 BUGFIX: Dont log stack trace for `InvalidHashException` in Production
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Configuration/Development/Settings.yaml
  Neos.Flow/Configuration/Settings.Error.yaml
Labels: Bug, 7.3
