Repository neos/flow-development-collection, pull requests merged in 2024-06, with the labels that each got.

#3360 BUGFIX: ReflectionService must always initialize
  Neos.Flow/Classes/Reflection/ReflectionService.php
Labels: Bug, 8.3

#3358 BUGFIX: Do proper resolving of FusionPathProxy
  Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php
Labels: Bug, 9.0

#3361 TASK: Benchmark basics
  Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
  Neos.Flow/Classes/Package.php
  Neos.Flow/Classes/Testing/RequestHandler/EmptyRequestHandler.php
  Neos.Flow/Classes/Testing/RequestHandler/RuntimeSequenceHttpRequestHandler.php
  Neos.Flow/Classes/Testing/RequestHandler/RuntimeSequenceInvokingRequestHandler.php
  Neos.Flow/Tests/PhpBench/Configuration/ConfigurationManagerBench.php
  Neos.Flow/Tests/PhpBench/Core/BootstrapBench.php
  Neos.Flow/Tests/PhpBench/Package/PackageManagerBench.php
  Neos.Flow/Tests/PhpBench/ResourceManagement/PersistentResourceBench.php
  Neos.Utility.Arrays/Tests/PhpBench/PositionalArraySorterBench.php
Labels: Task, 9.0

#3362 BUGFIX: First exception cannot be written in subcontext when booting
  Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Labels: Bug, 8.3

#3366 BUGFIX: Avoid insecure composer/composer versions
  Neos.Flow/composer.json
  composer.json
Labels: Bug, 7.3

#3365 BUGFIX: Streamline exit(1) to web response with HTTP status code 500
  Neos.Flow/Classes/Core/Bootstrap.php
Labels: Bug, 8.3

#3270 TASK: #3229 Followup improve docs
  Neos.Flow/Classes/ResourceManagement/Target/TargetInterface.php
Labels: Task, 9.0
