Repository neos/flow-development-collection, pull requests merged in 2024-04, with the labels that each got.

#3338 TASK: Introduce internal flow package key value object
  Neos.Flow/Classes/Composer/ComposerUtility.php
  Neos.Flow/Classes/Package/FlowPackageKey.php
  Neos.Flow/Classes/Package/PackageFactory.php
  Neos.Flow/Classes/Package/PackageInterface.php
  Neos.Flow/Classes/Package/PackageManager.php
  Neos.Flow/Tests/Unit/Package/FlowPackageKeyTest.php
  Neos.Flow/Tests/Unit/Package/PackageFactoryTest.php
  Neos.Flow/Tests/Unit/Package/PackageManagerTest.php
  Neos.FluidAdaptor/Classes/Core/Parser/Interceptor/ResourceInterceptor.php
Labels: Feature, Task, 9.0

#1514 !!!BUGFIX: Make any exception handable in renderingGroups by statusCode
  Neos.Flow/Classes/Error/AbstractExceptionHandler.php
  Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
Labels: T: PHP, P: Flow, 9.0

#3286 !!! FEATURE: `ViewInterface` returns PSR `StreamInterface`
  Neos.Flow/Classes/Error/AbstractExceptionHandler.php
  Neos.Flow/Classes/Error/DebugExceptionHandler.php
  Neos.Flow/Classes/Error/ProductionExceptionHandler.php
  Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
  Neos.Flow/Classes/Http/RequestHandler.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/View/AbstractView.php
  Neos.Flow/Classes/Mvc/View/JsonView.php
  Neos.Flow/Classes/Mvc/View/SimpleTemplateView.php
  Neos.Flow/Classes/Mvc/View/ViewInterface.php
  Neos.Flow/Tests/Functional/Mvc/ViewsConfiguration/Fixtures/TemplateView.php
  Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
  Neos.Flow/Tests/Unit/Mvc/View/JsonViewTest.php
  Neos.FluidAdaptor/Classes/View/AbstractTemplateView.php
  Neos.FluidAdaptor/Classes/View/StandaloneView.php
  Neos.FluidAdaptor/Tests/Functional/Core/Fixtures/ViewHelpers/Controller/View/CustomView.php
  Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php
  Neos.FluidAdaptor/Tests/Unit/View/AbstractTemplateViewTest.php
  Neos.Kickstarter/Classes/Service/GeneratorService.php
Labels: Feature, 9.0
