Repository neos/flow-development-collection, pull requests merged in 2024-11, with the labels that each got.

#3367 FEATURE: Introduce --help flag option for existing CLI commands
  Neos.Flow/Classes/Cli/RequestBuilder.php
  Neos.Flow/Classes/Command/HelpCommandController.php
Labels: Feature, 8.4

#3409 BUGFIX: Fix unit test for changed logging
  Neos.Flow.Log/Tests/Unit/Backend/FileBackendTest.php
Labels: Bug, 8.3

#3412 TASK: Drop code for PHP < 8
  Neos.Flow/Classes/Property/TypeConverter/MediaTypeConverter.php
Labels: Task, 8.3

#3387 TASK: Use `SCAN` for redis flush
  Neos.Cache/Classes/Backend/RedisBackend.php
Labels: Task, 8.3

#3388 BUGFIX: Make debugger more robust
  Neos.Flow/Classes/Error/Debugger.php
Labels: Bug, 8.4
