Repository neos/flow-development-collection, pull requests merged in 2024-01, with the labels that each got.

#3255 TASK: Correct symfony dependencies in Flow composer.json
  Neos.Flow/composer.json
Labels: Task, 8.3

#3257 Apply fixes from StyleCI
  Neos.Flow/Classes/Configuration/ConfigurationManager.php
Labels: 9.0

#3258 Apply fixes from StyleCI
  Neos.Flow/Classes/Configuration/ConfigurationManager.php
Labels: 7.3

#3256 TASK: Change version constraints for Neos packages to self.version
  Neos.Eel/composer.json
  Neos.Flow/composer.json
  Neos.FluidAdaptor/composer.json
  Neos.Kickstarter/composer.json
Labels: Task, 9.0

#3229 !!! TASK: Introduce `TargetInterface::onPublish` callback
  Neos.Flow/Classes/Command/ResourceCommandController.php
  Neos.Flow/Classes/ResourceManagement/Collection.php
  Neos.Flow/Classes/ResourceManagement/ResourceRepository.php
  Neos.Flow/Classes/ResourceManagement/Storage/FileSystemStorage.php
  Neos.Flow/Classes/ResourceManagement/Storage/PackageStorage.php
  Neos.Flow/Classes/ResourceManagement/Target/FileSystemSymlinkTarget.php
  Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php
  Neos.Flow/Classes/ResourceManagement/Target/TargetInterface.php
  Neos.Flow/Migrations/Mysql/Version20200908155620.php
  Neos.Flow/Migrations/Postgresql/Version20200908155621.php
  Neos.Flow/Tests/Unit/ResourceManagement/Storage/FileSystemStorageTest.php
  Neos.Flow/Tests/Unit/ResourceManagement/Target/FileSystemTargetTest.php
Labels: 9.0

#3220 TASK: Remove deprecated code
  Neos.Eel/Classes/ProtectedContext.php
  Neos.Flow/Classes/Mvc/ActionResponse.php
  Neos.Flow/Classes/Reflection/Exception/ClassLoadingForReflectionFailedException.php
Labels: Task, 9.0

#3260 TASK: Fix some nullable php doc types
  Neos.Eel/Classes/FlowQuery/FlowQuery.php
  Neos.Eel/Classes/Helper/StringHelper.php
  Neos.Flow/Classes/Aop/JoinPointInterface.php
  Neos.Flow/Classes/Cli/Response.php
  Neos.Flow/Classes/Configuration/ConfigurationSchemaValidator.php
  Neos.Flow/Classes/Core/ApplicationContext.php
  Neos.Flow/Classes/Error/AbstractExceptionHandler.php
  Neos.Flow/Classes/Http/Client/Browser.php
  Neos.Flow/Classes/Http/Cookie.php
  Neos.Flow/Classes/Http/Headers.php
  Neos.Flow/Classes/Http/Middleware/TrustedProxiesMiddleware.php
  Neos.Flow/Classes/I18n/Cldr/CldrRepository.php
  Neos.Flow/Classes/I18n/LocaleCollection.php
  Neos.Flow/Classes/I18n/Service.php
  Neos.Flow/Classes/Mvc/ActionRequest.php
  Neos.Flow/Classes/Mvc/Routing/Router.php
  Neos.Flow/Classes/Mvc/Routing/RouterCachingService.php
  Neos.Flow/Classes/Mvc/View/JsonView.php
  Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationProperty.php
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Classes/Property/PropertyMappingConfiguration.php
  Neos.Flow/Classes/Property/PropertyMappingConfigurationInterface.php
  Neos.Flow/Classes/ResourceManagement/ResourceManager.php
  Neos.Flow/Classes/Security/Policy/Role.php
  Neos.Flow/Classes/Session/Session.php
  Neos.Flow/Classes/Session/SessionInterface.php
  Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractLocaleAwareViewHelper.php
  Neos.FluidAdaptor/Classes/ViewHelpers/Form/AbstractFormViewHelper.php
  Neos.FluidAdaptor/Classes/ViewHelpers/Form/UploadViewHelper.php
  Neos.FluidAdaptor/Classes/ViewHelpers/FormViewHelper.php
Labels: Task, 9.0

#3265 FEATURE: Consider PHP attributes in proxy method building
  Neos.Flow/Classes/ObjectManagement/Exception/UnsupportedAttributeException.php
  Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethodGenerator.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassWithPhpAttributes.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/SampleMethodAttribute.php
  Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php
Labels: Feature, 9.0

#3269 BUGFIX: Fix documentation of `maximumThrowableDump` defaults
  Neos.Flow/Configuration/Settings.Log.yaml
Labels: Bug, 7.3

#3273 TASK: Followup 8.3 Revert "BUGFIX: Sanitize uploaded svg files for suspicious contents"
  Neos.Flow/composer.json
  composer.json
Labels: Task, 8.3

#3271 TASK: Adjust phpstan command to Neos' dev collection
  .composer.json
  Readme.rst
  composer.json
Labels: Task, 8.3

#3274 TASK: Correct doc types StringFrontend::get
  Neos.Cache/Classes/Frontend/FrontendInterface.php
  Neos.Cache/Classes/Frontend/StringFrontend.php
Labels: Task, 8.3

#3217 TASK: Level up to phpstan 2 (Flow 9 adjustments)
  Neos.Flow/Classes/Command/ResourceCommandController.php
  Neos.Flow/Classes/I18n/Xliff/Service/XliffReader.php
  Neos.Flow/Classes/Package.php
  Neos.Flow/Classes/Reflection/ReflectionService.php
  Neos.FluidAdaptor/Classes/Core/Parser/Interceptor/ResourceInterceptor.php
  Neos.FluidAdaptor/Classes/View/TemplatePaths.php
  bootstrap-phpstan.php
Labels: Task, 9.0

#3277 TASK: Ensure `IntegerConverter` converts DateTime to unix time stamp as int
  Neos.Flow/Classes/Property/TypeConverter/IntegerConverter.php
  Neos.Flow/Tests/Unit/Property/TypeConverter/IntegerConverterTest.php
Labels: Task, 9.0

#3278 !!! TASK: Fix `TextIterator::following` and `preceding`
  Neos.Utility.Unicode/Classes/TextIterator.php
Labels: 9.0

#3276 !!! TASK: Make `QueryInterface::logicalAnd` variadic
  Neos.Flow/Classes/Persistence/Doctrine/Query.php
  Neos.Flow/Classes/Persistence/QueryInterface.php
  phpstan.neon.dist
Labels: 9.0

#3151 BUGFIX `var_dump` skip static properties
  Neos.Flow/Classes/Error/Debugger.php
Labels: 9.0
