Repository neos/flow-development-collection, pull requests merged in 2025-02, with the labels that each got.

#3447 TASK: Cosmetic followup for #3443
  Neos.Flow/Classes/Reflection/ReflectionService.php
Labels: Task, 8.4

#3446 !!! TASK: Followup #3443 remove dead package freezing API's
  Neos.Flow/Classes/Command/CacheCommandController.php
  Neos.Flow/Classes/Command/PackageCommandController.php
  Neos.Flow/Classes/Package/PackageManager.php
  Neos.Flow/Configuration/Caches.yaml
Labels: 9.0

#3444 TASK: Add documentation how work with psr responses in controller
  Neos.Flow/Classes/Mvc/ActionResponse.php
  Neos.Flow/Classes/Mvc/Controller/AbstractController.php
  Neos.Flow/Classes/Mvc/Controller/ActionController.php
  Neos.Flow/Classes/Mvc/View/JsonView.php
Labels: Task, 9.0

#3449 BUGFIX: Avoid type error during `publishFile()`
  Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php
Labels: Bug, 8.3

#3224 FEATURE: Add depth option to `configuration:show`
  Neos.Flow/Classes/Command/ConfigurationCommandController.php
Labels: Feature, 9.0
