Repository neos/flow-development-collection, pull requests merged in 2025-01, with the labels that each got.

#3406 BUGFIX: Adjust to PHP 8.3 get_parent_class() deprecation
  Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
Labels: Bug, 8.3

#3413 TASK: Unify exception codes in Abstract(Template)View
  Neos.Flow/Classes/Mvc/View/AbstractView.php
  Neos.FluidAdaptor/Classes/View/AbstractTemplateView.php
Labels: Task, 8.3

#3431 BUGFIX: Add missing validation labels
  Neos.Flow/Resources/Private/Translations/de/ValidationErrors.xlf
  Neos.Flow/Resources/Private/Translations/en/ValidationErrors.xlf
Labels: Bug, 8.3

#3188 BUGFIX: Fix race-condition when initializing I18n Service
  Neos.Flow/Classes/I18n/Service.php
Labels: Bug, 8.3

#3434 TASK: Fix reflection test
  Neos.Flow/Tests/Functional/Reflection/ReflectionServiceTest.php
Labels: Task, 9.0

#3435 Avoid race-condition when reading localeCollection
  Neos.Flow/Classes/I18n/Service.php
  Neos.Flow/Tests/Unit/I18n/ServiceTest.php
Labels: 8.3

#3436 TASK: Run pipeline also in PHP 8.4
  .github/workflows/build.yml
Labels: Task, 8.3

#3438 BUGFIX: Silence warning in `readCacheFile()`
  Neos.Cache/Classes/Backend/SimpleFileBackend.php
Labels: Bug, 8.3

#3421 TASK: Fix override of runBare() in functional test
  Neos.FluidAdaptor/Tests/Functional/View/Fixtures/View/StandaloneView.php
  Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php
Labels: Task, 8.3

#3437 BUGFIX: Drop use of `E_STRICT` to fix PHP 8.4 deprecation
  Neos.Flow/Classes/Error/ErrorHandler.php
  Neos.Flow/Configuration/Development/Settings.yaml
  Neos.Flow/Configuration/Testing/Settings.yaml
Labels: Bug, 8.3

#3416 TASK: Handle non-integer error codes in throwabe FileStorage
  Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Labels: Task, 8.3
