Repository neos/flow-development-collection, pull requests merged in 2025-03, with the labels that each got.

#3456 TASK: Allow to return closure value from `withoutAuthorizationChecks()`
  Neos.Flow/Classes/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php
  Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php
  Neos.Flow/Classes/Security/Context.php
  Neos.Flow/Tests/Functional/Command/BehatHelperCommandController.php
Labels: Task, 9.0

#3459 FEATURE: Add CLDR-based date, time, and datetime formatting methods with "formatLength"
  Neos.Eel/Classes/Helper/DateHelper.php
  Neos.Eel/Tests/Unit/Helper/DateHelperTest.php
Labels: Feature, 8.4

#3455 BUGFIX: Set property to null via objects yaml
  Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
  Neos.Flow/Configuration/Testing/Objects.yaml
  Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
  Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/SingletonClassC.php
Labels: Bug, 8.3
